target: pl_modules.itransformer_module.iTransformerModule
params:
    num_features: 21
    seq_len: 28
    use_norm: True
    d_model: 128
    d_ff: 128
    dropout: 0
    activation: 'gelu'
    e_layers: 2
    output_attention: True
    factor: 1
    n_heads: 16
    loss: 'mse'
    window_size: 28
normalize: False