jumps: 900
date_format: "%Y-%m-%d"
start_date: "2022-01-01"
end_date: "2024-12-31"
root: "./data"
data_path: "./data/aiden_data/raw_data.csv"
train_interval: ["2022-01-01", "2023-12-31"]
val_interval: ["2024-01-01", "2024-05-31"]
test_interval: ["2024-06-01", "2024-12-31"]
additional_features: []