data_config: 'aiden_15m'
model: 'GRU_v'

name: 'gru'
max_epochs: 1000
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.005
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001