data_config: 'aiden_15m_additional'
model: 'iTransformer_v_additional'

name: 'aiden_itransformer_additional'
max_epochs: 3000
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.002
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001