data_config: 'aiden_15m_a15'
model: 'iTransformer_v_a15'

name: 'aiden_itransformer_a15'
max_epochs: 1500
use_volume: True

hyperparams:
    optimizer: 'adam'
    lr: 0.002
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001