data_config: 'aiden_15m'
model: 'iTransformer_nv'

name: 'aiden_itransformer'
max_epochs: 1000
use_volume: False

hyperparams:
    optimizer: 'adam'
    lr: 0.002
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.00001